-- Function: get_geographic_questions
-- Category: questions
-- Returns geographic regions to generate questions from, ranked by split quality
-- Spec: openspec/specs/algorithm/spec.md#geographic-vs-semantic-questions
CREATE OR REPLACE FUNCTION "game_logic"."get_geographic_questions" (
  "p_session_id" "uuid",
  "p_candidates" JSONB,
  "p_limit" INTEGER DEFAULT NULL
) returns TABLE (
  "geographic_region_id" "uuid",
  "region_name" "text",
  "region_level" "text",
  "split_quality" DOUBLE PRECISION,
  "yes_count" INTEGER,
  "no_count" INTEGER,
  "question_text" TEXT
) language plpgsql
SET
  search_path = public,
  game_logic,
  extensions AS $$
DECLARE
  v_shallowest_confirmed_level geographic_level;
  v_confirmed_regions geometry[];
BEGIN
  -- Find the shallowest (broadest) confirmed geographic level
  SELECT MIN(gr.level::geographic_level)
  INTO v_shallowest_confirmed_level
  FROM game_answers ga
  JOIN geographic_regions gr ON gr.id = ga.geographic_region_id
  WHERE ga.session_id = p_session_id
    AND ga.answer = 'yes'::answer_value
    AND ga.geographic_region_id IS NOT NULL;

  -- Get all confirmed regions as geometries for spatial filtering
  SELECT ARRAY_AGG(gr.geom)
  INTO v_confirmed_regions
  FROM game_answers ga
  JOIN geographic_regions gr ON gr.id = ga.geographic_region_id
  WHERE ga.session_id = p_session_id
    AND ga.answer = 'yes'::answer_value
    AND ga.geographic_region_id IS NOT NULL;

  RETURN QUERY
  WITH candidate_geoms AS (
    -- Convert candidate JSONB to geometries (supports Point, Polygon, MultiPolygon)
    SELECT 
      (c->>'id')::uuid as place_id,
      ST_GeomFromText((c->>'geom_wkt')::text, 4326) as geom
    FROM jsonb_array_elements(p_candidates) c
  ),
  region_splits AS (
    -- Calculate how each region splits the candidates
    SELECT
      gr.id,
      gr.name,
      gr.level,
      COALESCE(qs.effectiveness_score, 0.5) as effectiveness_score,
      COALESCE(qs.times_asked, 0) as times_asked,
      -- Count candidates that intersect with region (YES answers)
      COUNT(*) FILTER (WHERE ST_Intersects(cg.geom, gr.geom)) as yes_count,
      -- Count candidates that don't intersect with region (NO answers)
      COUNT(*) FILTER (WHERE NOT ST_Intersects(cg.geom, gr.geom)) as no_count,
      -- Information gain: 1.0 = perfect 50/50 split, 0.0 = all yes or all no
      CASE 
        WHEN COUNT(*) = 0 THEN 0.0
        ELSE 1.0 - ABS(0.5 - (COUNT(*) FILTER (WHERE ST_Intersects(cg.geom, gr.geom))::float / COUNT(*)))
      END as information_gain
    FROM geographic_regions gr
    CROSS JOIN candidate_geoms cg
    LEFT JOIN game_logic.question_stats qs ON qs.geographic_region_id = gr.id
    WHERE
      -- Don't ask same region twice
      gr.id NOT IN (
        SELECT ga.geographic_region_id
        FROM game_answers ga
        WHERE ga.session_id = p_session_id
          AND ga.geographic_region_id IS NOT NULL
      )
      -- Level filter: once a level is confirmed, only ask about deeper levels
      AND (
        v_shallowest_confirmed_level IS NULL
        OR gr.level::geographic_level > v_shallowest_confirmed_level
      )
      -- Spatial filter: must intersect with confirmed regions (if any)
      AND (
        v_confirmed_regions IS NULL
        OR EXISTS (
          SELECT 1
          FROM UNNEST(v_confirmed_regions) AS confirmed_geom
          WHERE ST_Intersects(confirmed_geom, gr.geom)
        )
      )
    GROUP BY gr.id, gr.name, gr.level, qs.effectiveness_score, qs.times_asked
    HAVING 
      -- CRITICAL: Only return regions that actually SPLIT the candidates
      COUNT(*) FILTER (WHERE ST_Intersects(cg.geom, gr.geom)) > 0  -- Some YES
      AND COUNT(*) FILTER (WHERE NOT ST_Intersects(cg.geom, gr.geom)) > 0  -- Some NO
  )
  SELECT
    rs.id as geographic_region_id,
    rs.name as region_name,
    rs.level as region_level,
    rs.information_gain as split_quality,
    rs.yes_count::INTEGER,
    rs.no_count::INTEGER,
    NULL as question_text  -- Will be generated by LLM later
  FROM region_splits rs
  -- Order by split quality (best splits first), then effectiveness
  ORDER BY rs.information_gain DESC, rs.effectiveness_score DESC, rs.times_asked ASC
  LIMIT p_limit;
END;
$$;


ALTER FUNCTION "game_logic"."get_geographic_questions" (
  "p_session_id" "uuid",
  "p_candidates" JSONB,
  "p_limit" INTEGER
) owner TO "postgres";


comment ON function "game_logic"."get_geographic_questions" (
  "p_session_id" "uuid",
  "p_candidates" JSONB,
  "p_limit" INTEGER
) IS 'Returns geographic regions to generate questions from (e.g., "Is it in {region_name}?").

CANDIDATE-AWARE: Uses actual place geometries (Point, Polygon, MultiPolygon) from candidates to calculate split quality.

Uses ST_Intersects for accurate geometry-based split calculation (works for all geometry types).

Filters by:
1. Level hierarchy: Must be deeper than shallowest confirmed level
2. Spatial intersection: Must intersect with confirmed regions
3. Not already asked in this session
4. MUST SPLIT CANDIDATES: Only returns regions where some candidates intersect and some don''t

Ranking:
1. split_quality (1.0 = perfect 50/50 split, 0.5 = useless question)

Progressive narrowing: continent → country

Returns: geographic_region_id, region_name, region_level, split_quality, yes_count, no_count, question_text.
Consistent return format with get_semantic_questions for use by select_best_question.';
