-- Function: get_semantic_questions
-- Category: questions
-- Returns traits to generate semantic questions from, ranked by split quality
-- Spec: openspec/specs/algorithm/spec.md#question-selection-algorithm
CREATE OR REPLACE FUNCTION "game_logic"."get_semantic_questions" (
  "p_session_id" "uuid",
  "p_candidates" JSONB,
  "p_limit" INTEGER DEFAULT NULL
) returns TABLE (
  "trait_id" TEXT,
  "trait_clause" TEXT,
  "trait_category" TEXT,
  "split_quality" DOUBLE PRECISION,
  "yes_count" INTEGER,
  "no_count" INTEGER,
  "question_text" TEXT
) language plpgsql
SET
  search_path = public, extensions, game_logic AS $$
DECLARE
  v_candidate_count INT;
BEGIN
  v_candidate_count := jsonb_array_length(p_candidates);
  
  IF v_candidate_count <= 1 THEN
    RETURN;  -- No point asking questions with 0-1 candidates
  END IF;
  
  RETURN QUERY
  WITH candidate_places AS (
    -- Extract candidate place IDs and their embeddings
    SELECT 
      (c->>'id')::uuid as place_id,
      pe.embedding as place_embedding
    FROM jsonb_array_elements(p_candidates) c
    JOIN places p ON p.id = (c->>'id')::uuid
    JOIN embeddings pe ON pe.id = p.embedding_id
  ),
  trait_similarities AS (
    -- Calculate embedding similarity between each trait and each candidate place
    SELECT
      t.id as trait_id,
      t.clause,
      cp.place_id,
      -- Cosine similarity: 1 - cosine_distance
      (1 - (te.embedding::vector <=> cp.place_embedding::vector)) as similarity
    FROM traits t
    JOIN embeddings te ON te.id = t.embedding_id
    CROSS JOIN candidate_places cp
    WHERE
      -- Don't ask same trait twice
      t.id NOT IN (
        SELECT ga.trait_id
        FROM game_answers ga
        WHERE ga.session_id = p_session_id
          AND ga.trait_id IS NOT NULL
      )
  ),
  trait_splits AS (
    -- Calculate split quality for each trait using similarity threshold
    SELECT
      ts.trait_id,
      ts.clause,
      'general'::text as category,
      -- Get similarity threshold from config
      get_config_float('traits.similarity_threshold') as similarity_threshold,
      -- Count candidates that match trait (similarity >= threshold)
      COUNT(*) FILTER (WHERE ts.similarity >= get_config_float('traits.similarity_threshold')) as yes_count,
      -- Count candidates that don't match trait (similarity < threshold)
      COUNT(*) FILTER (WHERE ts.similarity < get_config_float('traits.similarity_threshold')) as no_count,
      -- Split quality: 1.0 = perfect 50/50 split, 0.5 = all yes or all no
      CASE 
        WHEN v_candidate_count = 0 THEN 0.0
        ELSE 1.0 - ABS(0.5 - (COUNT(*) FILTER (WHERE ts.similarity >= get_config_float('traits.similarity_threshold'))::float / v_candidate_count))
      END as split_quality
    FROM trait_similarities ts
    GROUP BY ts.trait_id, ts.clause
    HAVING 
      -- CRITICAL: Only return traits that actually SPLIT the candidates
      COUNT(*) FILTER (WHERE ts.similarity >= get_config_float('traits.similarity_threshold')) > 0  -- Some YES
      AND COUNT(*) FILTER (WHERE ts.similarity < get_config_float('traits.similarity_threshold')) > 0  -- Some NO
  )
  SELECT
    ts.trait_id as id,
    ts.clause,
    ts.category,
    ts.split_quality,
    ts.yes_count::INTEGER,
    ts.no_count::INTEGER,
    NULL as question_text  -- Will be generated by LLM later
  FROM trait_splits ts
  ORDER BY ts.split_quality DESC
  LIMIT p_limit;
END;
$$;


ALTER FUNCTION "game_logic"."get_semantic_questions" (
  "p_session_id" "uuid",
  "p_candidates" JSONB,
  "p_limit" INTEGER
) owner TO "postgres";


comment ON function "game_logic"."get_semantic_questions" (
  "p_session_id" "uuid",
  "p_candidates" JSONB,
  "p_limit" INTEGER
) IS 'Returns traits to generate semantic questions from, ranked by split quality.

CANDIDATE-AWARE: Uses place_traits to determine which places have which traits.

Split quality formula (from spec):
- fraction_matching = count(places with trait) / candidate_count
- split_quality = 1 - |0.5 - fraction_matching|

Filters by:
1. Not already asked in this session
2. MUST SPLIT CANDIDATES: Only returns traits where some candidates have it and some don''t

Orders by:
1. Split quality (perfect 50/50 split = 1.0)

Returns: trait info + yes_count, no_count, split_quality for analysis.
Questions are generated on-the-fly from trait clauses.';
