-- Function: get_semantic_questions
-- Category: questions
-- Returns traits to generate semantic questions from, ranked by split quality
-- Uses place_traits relationship (ground truth) for split quality calculation
-- Spec: docs/architecture/algorithm.md#question-selection
CREATE OR REPLACE FUNCTION "game_logic"."get_semantic_questions" (
  "p_session_id" "uuid",
  "p_candidates" JSONB,
  "p_limit" INTEGER DEFAULT NULL
) returns TABLE (
  "trait_id" UUID,
  "trait_clause" TEXT,
  "trait_category" TEXT,
  "split_quality" DOUBLE PRECISION,
  "yes_count" INTEGER,
  "no_count" INTEGER,
  "question_text" TEXT
) language plpgsql
SET
  search_path = public,
  extensions,
  game_logic AS $$
DECLARE
  v_candidate_count INT;
  v_description_embedding vector(384);
BEGIN
  v_candidate_count := jsonb_array_length(p_candidates);
  
  IF v_candidate_count <= 1 THEN
    RETURN;  -- No point asking questions with 0-1 candidates
  END IF;

  -- Get session description embedding for tiebreaker
  SELECT e.embedding INTO v_description_embedding
  FROM game_sessions gs
  JOIN embeddings e ON e.id = gs.embedding_id
  WHERE gs.id = p_session_id;
  
  RETURN QUERY
  WITH candidate_ids AS (
    -- Extract candidate place IDs
    SELECT (c->>'id')::uuid as place_id
    FROM jsonb_array_elements(p_candidates) c
  ),
  trait_counts AS (
    -- Count how many candidates have each trait using place_traits (ground truth)
    SELECT
      t.id as trait_id,
      t.clause,
      t.embedding_id,
      COUNT(pt.place_id) FILTER (WHERE pt.place_id IN (SELECT place_id FROM candidate_ids)) as yes_count
    FROM traits t
    LEFT JOIN place_traits pt ON pt.trait_id = t.id
    WHERE
      -- Don't ask same trait twice
      t.id NOT IN (
        SELECT ga.trait_id
        FROM game_answers ga
        WHERE ga.session_id = p_session_id
          AND ga.trait_id IS NOT NULL
      )
    GROUP BY t.id, t.clause, t.embedding_id
  ),
  trait_splits AS (
    -- Calculate split quality for each trait
    SELECT
      tc.trait_id,
      tc.clause,
      tc.embedding_id,
      'general'::text as category,
      tc.yes_count::INTEGER,
      (v_candidate_count - tc.yes_count)::INTEGER as no_count,
      -- Split quality: 1.0 = perfect 50/50 split, 0.5 = all yes or all no
      (1.0 - ABS(0.5 - (tc.yes_count::float / v_candidate_count)))::DOUBLE PRECISION as split_quality
    FROM trait_counts tc
    WHERE
      -- CRITICAL: Only return traits that actually SPLIT the candidates
      tc.yes_count > 0  -- Some candidates have this trait
      AND tc.yes_count < v_candidate_count  -- Some candidates don't have it
  )
  SELECT
    ts.trait_id,
    ts.clause,
    ts.category,
    ts.split_quality,
    ts.yes_count,
    ts.no_count,
    NULL::TEXT as question_text  -- Will be generated by LLM later
  FROM trait_splits ts
  LEFT JOIN embeddings te ON te.id = ts.embedding_id
  ORDER BY 
    ts.split_quality DESC,
    -- Tiebreaker: prefer traits most similar to description
    CASE WHEN v_description_embedding IS NOT NULL AND te.embedding IS NOT NULL
      THEN (1 - (te.embedding <=> v_description_embedding))
      ELSE 0
    END DESC
  LIMIT p_limit;
END;
$$;


ALTER FUNCTION "game_logic"."get_semantic_questions" (
  "p_session_id" "uuid",
  "p_candidates" JSONB,
  "p_limit" INTEGER
) owner TO "postgres";


comment ON function "game_logic"."get_semantic_questions" (
  "p_session_id" "uuid",
  "p_candidates" JSONB,
  "p_limit" INTEGER
) IS 'Returns traits to generate semantic questions from, ranked by split quality.

Uses place_traits relationship (ground truth) to determine which candidates have which traits.
This is faster and more accurate than embedding similarity.

Split quality formula (from docs/architecture/algorithm.md#question-selection):
- yes_count = count(candidates that have this trait via place_traits)
- no_count = candidate_count - yes_count
- split_quality = 1 - |0.5 - (yes_count / candidate_count)|

Filters by:
1. Not already asked in this session
2. MUST SPLIT CANDIDATES: Only returns traits where some candidates have it and some don''t

Orders by:
1. Split quality (perfect 50/50 split = 1.0)
2. Tiebreaker: trait similarity to description (using embeddings)

Returns: trait info + yes_count, no_count, split_quality for analysis.
Question text is generated on-the-fly by LLM from trait clauses.';
