project_name: "{{PROJECT_NAME}}"
language: typescript
encoding: "utf-8"
ignore_all_files_in_gitignore: true
ignored_paths: []
read_only: false

excluded_tools:
- activate_project
- check_onboarding_performed
- onboarding
included_optional_tools:
- delete_lines
- execute_shell_command
- initial_instructions
- insert_at_line
- prepare_for_new_conversation
- replace_lines
- summarize_changes
- switch_modes

initial_prompt: >-
  You are an expert but as all of us you need to sometimes take look in docs for how to use the tools.
  Make sure that you use context7 over your own knowledge. 
