project_name: "10x-mapmaster"
language: typescript
encoding: "utf-8"
ignore_all_files_in_gitignore: true
ignored_paths: []
read_only: false

excluded_tools:
- activate_project
- check_onboarding_performed
included_optional_tools:
- initial_instructions
- delete_lines
- insert_at_line
- replace_lines
- summarize_changes
- switch_modes

initial_prompt: ""
