-- Seed places for MVP testing
INSERT INTO places (name, lat, lng, descriptors) VALUES
  ('Eiffel Tower', 48.8584, 2.2945, '{"country_code":"fr","type":"tower","class":"tourism","address":{"city":"Paris","country":"France"}}'::jsonb),
  ('Big Ben', 51.5007, -0.1246, '{"country_code":"gb","type":"tower","class":"tourism","address":{"city":"London","country":"United Kingdom"}}'::jsonb),
  ('Tower Bridge', 51.5055, -0.0754, '{"country_code":"gb","type":"bridge","class":"tourism","address":{"city":"London","country":"United Kingdom"}}'::jsonb),
  ('Colosseum', 41.8902, 12.4922, '{"country_code":"it","type":"monument","class":"tourism","address":{"city":"Rome","country":"Italy"}}'::jsonb),
  ('Sagrada Familia', 41.4036, 2.1744, '{"country_code":"es","type":"place_of_worship","class":"tourism","address":{"city":"Barcelona","country":"Spain"}}'::jsonb),
  ('Brandenburg Gate', 52.5163, 13.3777, '{"country_code":"de","type":"monument","class":"tourism","address":{"city":"Berlin","country":"Germany"}}'::jsonb),
  ('Acropolis', 37.9715, 23.7267, '{"country_code":"gr","type":"monument","class":"tourism","address":{"city":"Athens","country":"Greece"}}'::jsonb),
  ('Mount Everest', 27.9881, 86.9250, '{"country_code":"np","type":"peak","class":"natural","address":{"country":"Nepal"}}'::jsonb),
  ('Lake Geneva', 46.4534, 6.5615, '{"country_code":"ch","type":"lake","class":"natural","address":{"country":"Switzerland"}}'::jsonb),
  ('Mount Fuji', 35.3606, 138.7274, '{"country_code":"jp","type":"peak","class":"natural","address":{"country":"Japan"}}'::jsonb),
  ('Grand Canyon', 36.1069, -112.1129, '{"country_code":"us","type":"canyon","class":"natural","address":{"state":"Arizona","country":"United States"}}'::jsonb),
  ('Niagara Falls', 43.0828, -79.0763, '{"country_code":"ca","type":"waterfall","class":"natural","address":{"country":"Canada"}}'::jsonb),
  ('Statue of Liberty', 40.6892, -74.0445, '{"country_code":"us","type":"monument","class":"tourism","address":{"city":"New York","country":"United States"}}'::jsonb),
  ('Sydney Opera House', -33.8568, 151.2153, '{"country_code":"au","type":"theatre","class":"tourism","address":{"city":"Sydney","country":"Australia"}}'::jsonb),
  ('Taj Mahal', 27.1751, 78.0421, '{"country_code":"in","type":"monument","class":"tourism","address":{"city":"Agra","country":"India"}}'::jsonb),
  ('Great Wall of China', 40.4319, 116.5704, '{"country_code":"cn","type":"monument","class":"tourism","address":{"country":"China"}}'::jsonb),
  ('Machu Picchu', -13.1631, -72.5450, '{"country_code":"pe","type":"monument","class":"tourism","address":{"country":"Peru"}}'::jsonb),
  ('Christ the Redeemer', -22.9519, -43.2105, '{"country_code":"br","type":"monument","class":"tourism","address":{"city":"Rio de Janeiro","country":"Brazil"}}'::jsonb),
  ('Burj Khalifa', 25.1972, 55.2744, '{"country_code":"ae","type":"tower","class":"tourism","address":{"city":"Dubai","country":"United Arab Emirates"}}'::jsonb),
  ('Pyramids of Giza', 29.9792, 31.1342, '{"country_code":"eg","type":"monument","class":"tourism","address":{"city":"Cairo","country":"Egypt"}}'::jsonb);
