-- ============================================================================
-- Seed Data: Places and Questions
-- ============================================================================
-- Initial seed data for testing and gameplay
-- Places start with only names (like user input) - enrichment happens via scripts
-- Questions include type and geographic regions for dual-matching system

-- ============================================================================
-- SEED PLACES (20 famous landmarks - name only)
-- ============================================================================
-- Enrichment (lat/lng, descriptors, embeddings) will be added by generate-places-seed.ts

INSERT INTO places (name) VALUES
  ('Eiffel Tower'),
  ('Big Ben, London'),
  ('Tower Bridge'),
  ('Colosseum'),
  ('Sagrada Familia'),
  ('Brandenburg Gate'),
  ('Acropolis'),
  ('Mount Everest'),
  ('Lake Geneva'),
  ('Mount Fuji'),
  ('Grand Canyon'),
  ('Niagara Falls'),
  ('Statue of Liberty'),
  ('Sydney Opera House'),
  ('Taj Mahal'),
  ('Great Wall of China'),
  ('Machu Picchu'),
  ('Christ the Redeemer'),
  ('Burj Khalifa'),
  ('Pyramids of Giza');

-- ============================================================================
-- SEED QUESTIONS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- GEOGRAPHIC QUESTIONS (PostGIS spatial filtering with bounding boxes)
-- ----------------------------------------------------------------------------

-- Continents
INSERT INTO questions (text, question_type, geographic_region) VALUES
  ('Is it in Europe?', 'geographic', '{"bbox": [-10, 36, 40, 71]}'),
  ('Is it in Asia?', 'geographic', '{"bbox": [26, -10, 180, 77]}'),
  ('Is it in Africa?', 'geographic', '{"bbox": [-18, -35, 52, 37]}'),
  ('Is it in North America?', 'geographic', '{"bbox": [-170, 15, -50, 72]}'),
  ('Is it in South America?', 'geographic', '{"bbox": [-82, -56, -34, 13]}'),
  ('Is it in Oceania?', 'geographic', '{"bbox": [110, -47, 180, -10]}');

-- Hemispheres
INSERT INTO questions (text, question_type, geographic_region) VALUES
  ('Is it in the Northern Hemisphere?', 'geographic', '{"bbox": [-180, 0, 180, 90]}'),
  ('Is it in the Southern Hemisphere?', 'geographic', '{"bbox": [-180, -90, 180, 0]}'),
  ('Is it in the Western Hemisphere?', 'geographic', '{"bbox": [-180, -90, 0, 90]}'),
  ('Is it in the Eastern Hemisphere?', 'geographic', '{"bbox": [0, -90, 180, 90]}');

-- Sub-regions
INSERT INTO questions (text, question_type, geographic_region) VALUES
  ('Is it in the Mediterranean region?', 'geographic', '{"bbox": [-6, 30, 36, 46]}'),
  ('Is it in the Middle East?', 'geographic', '{"bbox": [34, 12, 63, 42]}'),
  ('Is it in Southeast Asia?', 'geographic', '{"bbox": [92, -11, 141, 28]}'),
  ('Is it in Scandinavia?', 'geographic', '{"bbox": [4, 55, 31, 71]}'),
  ('Is it in the Caribbean?', 'geographic', '{"bbox": [-85, 10, -60, 27]}'),
  ('Is it in Central America?', 'geographic', '{"bbox": [-92, 7, -77, 18]}');

-- Climate/Latitude zones
INSERT INTO questions (text, question_type, geographic_region) VALUES
  ('Is it in the tropics (between the Tropics of Cancer and Capricorn)?', 'geographic', '{"bbox": [-180, -23.5, 180, 23.5]}'),
  ('Is it in the Arctic region (above 66°N)?', 'geographic', '{"bbox": [-180, 66, 180, 90]}'),
  ('Is it near the equator (within 10° latitude)?', 'geographic', '{"bbox": [-180, -10, 180, 10]}');

-- ----------------------------------------------------------------------------
-- SEMANTIC QUESTIONS (pgvector similarity matching via embeddings)
-- ----------------------------------------------------------------------------
-- Embeddings will be generated by generate-questions-seed.ts

-- Feature type
INSERT INTO questions (text, question_type) VALUES
  ('Is it a natural feature?', 'semantic'),
  ('Is it in a major city?', 'semantic'),
  ('Is it in a capital city?', 'semantic'),
  ('Is it a bridge or tower?', 'semantic');

-- Geographic features
INSERT INTO questions (text, question_type) VALUES
  ('Is it near an ocean or sea?', 'semantic'),
  ('Is it near a river or lake?', 'semantic'),
  ('Is it very tall (over 200 meters)?', 'semantic');

-- Historical period
INSERT INTO questions (text, question_type) VALUES
  ('Was it built in ancient times?', 'semantic'),
  ('Was it built in medieval times?', 'semantic'),
  ('Is it from the modern era (after 1800)?', 'semantic');

-- Characteristics
INSERT INTO questions (text, question_type) VALUES
  ('Is it a religious or spiritual site?', 'semantic'),
  ('Is it made primarily of stone?', 'semantic'),
  ('Is it made of metal or steel?', 'semantic'),
  ('Can you climb to the top of it?', 'semantic');
